drop table if exists items CASCADE ;
drop table if exists tags CASCADE ;
drop table if exists users CASCADE ;
create table items (id bigint generated by default as identity, owner_id bigint, url varchar(255), primary key (id));
create table tags (item_id bigint not null, name varchar(255));
create table users (id bigint generated by default as identity, email varchar(255), first_name varchar(255) not null, last_name varchar(255), password varchar(255), registration_date timestamp, state varchar(255), primary key (id));
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table items add constraint FKe37yi0i6rmaqcqickvb1vty22 foreign key (owner_id) references users;
alter table tags add constraint FKs5i8nws6q9to84v4mmn1xsmn5 foreign key (item_id) references items;
